version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database

  migrate:
    build: .
    environment:
      MIGRATE_URI: "postgres://your_username:your_password@postgres:5432/your_database"
    depends_on:
      - postgres
    volumes:
      - ./migrations.py:/app/migrations.py

